In [1]:
!pip install scikit-learn==0.23.1

  Using cached scikit-learn-0.23.1.tar.gz (7.2 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'


  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Mohammad\anaconda3\python.exe' 'C:\Users\Mohammad\AppData\Local\Temp\pip-standalone-pip-2r338abs\__env_pip__.zip\pip' install --ignore-installed --no-user --prefix 'C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-zx0qfwnd\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.28.5' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation == '"'"'CPython'"'"'' 'numpy==1.14.0; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation != '"'"'CPython'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'

In [2]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
%matplotlib inline 
import matplotlib.pyplot as plt

      libraries lapack_atlas not found in C:\Users\Mohammad\anaconda3\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in C:\Users\Mohammad\anaconda3\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\Users\Mohammad\anaconda3\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in C:\Users\Mohammad

In [4]:
df=pd.read_csv('heart.csv')
df.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [18]:
df.dtypes

age           int64
sex           int64
cp            int64
trtbps        int64
chol          int64
fbs           int64
restecg       int64
thalachh      int64
exng          int64
oldpeak     float64
slp           int64
caa           int64
thall         int64
output        int64
dtype: object

In [23]:
df = df[pd.to_numeric(df['oldpeak'], errors='coerce').notnull()]
df['oldpeak'] = df['oldpeak'].astype('int')

In [24]:
df.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output'],
      dtype='object')

In [25]:
# داده های مورد نیاز ایکس رو جدا میکنیم تا روشون کار انجام بدیم
feature_df = df[['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall']]
X = np.asarray(feature_df)
X[0:5]

array([[ 63,   1,   3, 145, 233,   1,   0, 150,   0,   2,   0,   0,   1],
       [ 37,   1,   2, 130, 250,   0,   1, 187,   0,   3,   0,   0,   2],
       [ 41,   0,   1, 130, 204,   0,   0, 172,   0,   1,   2,   0,   2],
       [ 56,   1,   1, 120, 236,   0,   1, 178,   0,   0,   2,   0,   2],
       [ 57,   0,   0, 120, 354,   0,   1, 163,   1,   0,   2,   0,   2]],
      dtype=int64)

In [27]:
# ایگرگ (کلاس) رو هم جدا میکنیم
df['output'] = df['output'].astype('int')
y = np.asarray(df['output'])
y [0:5]

array([1, 1, 1, 1, 1])

# Train/Test dataset

In [28]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (242, 13) (242,)
Test set: (61, 13) (61,)


# Modeling (SVM with Scikit-learn)

In [29]:
 from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_train, y_train)

SVC()

In [30]:
# حالا که ترین رو انجام دادیم، روی داده های تستمون چکش میکنیم
yhat = clf.predict(X_test)
yhat [0:5]

array([1, 1, 1, 1, 0])

# Evaluation

In [31]:
from sklearn.metrics import classification_report, confusion_matrix
import itertools

In [35]:
# اگر  فقد اف وان اسکور رو بخوایم

from sklearn.metrics import f1_score
f1_score(y_test, yhat, average='weighted') 

0.6511395441823271

In [37]:
# و اگر بخوایم اندیس ژاکار رو تست کنیم

from sklearn.metrics import jaccard_score
jaccard_score(y_test, yhat,pos_label=1)

0.6078431372549019

* مشاهده میکنیم که این الگوریتم پاسخ چندان مناسبی نمیدهد